### ISSUE TITLE
No such file or directory error related to Bootstrap CSS source map + Chrome

### ISSUE THREAD

**Issue by scottengle** [himynameisdave/eggs-genny#37]
I'm seeing a "no such file or directory" error in Chrome when I render the default app in the browser. 

The error I see in the console:

[09:59:37] Using gulpfile ~/git/ppp/gulpfile.js
[09:59:37] Starting 'serve-me'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Server running at http://localhost:6969/
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[09:59:37] Finished 'serve-me' after 2.35 ms
[09:59:37] Starting 'reload-me'...
[09:59:37] Finished 'reload-me' after 144 ms
[09:59:37] Starting 'default'...
[09:59:37] Finished 'default' after 4.99 μs
+++++++++++++++++++++++++++++++++++++++++++++++
I've reloaded your page, sir!
    March 13, 2015 at 10:00:08
+++++++++++++++++++++++++++++++++++++++++++++++
Error: ENOENT, no such file or directory '/Users/englsa2/git/ppp/app/lib/css/bootstrap.css.map'
    at Object.fs.statSync (fs.js:695:18)
    at Object.handle (/Users/englsa2/git/ppp/node_modules/dirlist/lib/dirlist.js:9:9)
    at next (/Users/englsa2/git/ppp/node_modules/connect/lib/proto.js:190:15)
    at Object.favicon [as handle](/Users/englsa2/git/ppp/node_modules/connect/lib/middleware/favicon.js:77:7)
    at next (/Users/englsa2/git/ppp/node_modules/connect/lib/proto.js:190:15)
    at Function.app.handle (/Users/englsa2/git/ppp/node_modules/connect/lib/proto.js:198:3)
    at Server.app (/Users/englsa2/git/ppp/node_modules/connect/lib/connect.js:65:37)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2112:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:121:23)

Based on this link [CSS Preprocessors](https://developer.chrome.com/devtools/docs/css-preprocessors#toc-how-css-source-maps-work), I tracked the cause of the error down to line 6566 in the Bootstrap CSS:

`/*# sourceMappingURL=bootstrap.css.map */`

I have fixed this in my local fork and will submit a pull request for it shortly for you to review.

**Comment by himynameisdave** [comment]
Thanks a bunch!

**Comment by scottengle** [comment]
Pull request submitted:

https://github.com/himynameisdave/eggs-genny/pull/38

Thanks!

**Comment by himynameisdave** [comment]
closed by #38
